/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/material/core/ripple/ripple';
import * as import9 from '@angular/material/button/button';
import * as import10 from '@angular/material/card/card';
import * as import11 from '@angular/material/checkbox/checkbox';
import * as import12 from '@angular/material/core/line/line';
import * as import13 from '@angular/material/grid-list/grid-list';
import * as import14 from '@angular/material/input/input';
import * as import15 from '@angular/material/list/list';
import * as import16 from '@angular/material/progress-bar/progress-bar';
import * as import17 from '@angular/material/progress-circle/progress-circle';
import * as import18 from '@angular/material/sidenav/sidenav';
import * as import19 from '@angular/material/core/portal/portal-directives';
import * as import20 from '@angular/material/tabs/tabs';
import * as import21 from '@angular/material/toolbar/toolbar';
import * as import22 from '@angular/material/core/rtl/dir';
import * as import23 from '@angular/material/core/a11y/index';
import * as import24 from '@angular/material/button-toggle/button-toggle';
import * as import25 from '@angular/material/core/overlay/overlay-directives';
import * as import26 from '@angular/material/dialog/dialog';
import * as import27 from '@angular/material/icon/icon';
import * as import28 from '@angular/material/menu/menu';
import * as import29 from '@angular/material/radio/radio';
import * as import30 from '@angular/material/slider/slider';
import * as import31 from '@angular/material/slide-toggle/slide-toggle';
import * as import32 from '@angular/material/snack-bar/snack-bar';
import * as import33 from '@angular/material/tooltip/tooltip';
import * as import34 from '@angular/material/core/compatibility/style-compatibility';
import * as import35 from '@angular/material/module';
import * as import36 from '../shared/shared.module';
import * as import37 from '../core/core.module';
import * as import38 from '@angular/router/src/router_module';
import * as import39 from '@ngrx/store/src/ng2';
import * as import40 from '@ngrx/store-devtools/src/instrument';
import * as import41 from '@angular/core/src/application_init';
import * as import42 from '@angular/core/src/testability/testability';
import * as import43 from '@angular/core/src/application_ref';
import * as import44 from '@angular/common/src/localization';
import * as import45 from '@angular/core/src/linker/compiler';
import * as import46 from '@angular/material/core/gestures/MdGestureConfig';
import * as import47 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import48 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import49 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import50 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import51 from '@angular/core/src/linker/view_utils';
import * as import52 from '@angular/platform-browser/src/browser/title';
import * as import53 from '@angular/forms/src/form_builder';
import * as import54 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import55 from '@angular/http/src/backends/browser_xhr';
import * as import56 from '@angular/http/src/base_response_options';
import * as import57 from '@angular/http/src/backends/xhr_backend';
import * as import58 from '@angular/http/src/base_request_options';
import * as import59 from '@angular/material/core/a11y/live-announcer';
import * as import60 from '@angular/material/core/a11y/interactivity-checker';
import * as import61 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import62 from '@angular/material/core/overlay/overlay-container';
import * as import63 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import64 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import65 from '@angular/material/core/overlay/overlay';
import * as import66 from '@angular/material/icon/icon-registry';
import * as import67 from '@ngrx/store/src/dispatcher';
import * as import68 from '../core/loading-bar/loading-bar.actions';
import * as import69 from '../core/loading-bar/loading-bar.service';
import * as import70 from '../core/alert/alert.actions';
import * as import71 from '../core/alert/alert.service';
import * as import72 from '../core/storage';
import * as import73 from '../core/profile/profile.service';
import * as import74 from '@angular/router/src/url_tree';
import * as import75 from '@angular/router/src/router_outlet_map';
import * as import76 from '@angular/common/src/location/location';
import * as import77 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import78 from '../core/guards/auth-guard.service';
import * as import79 from '../core/guards/super-admin-auth-guard.service';
import * as import80 from '../core/guards/authenticated-auth-guard.service';
import * as import81 from '../core/services/http-exceptions.service';
import * as import82 from '../core/services/form-validation.service';
import * as import83 from '../core/auth-store/logged-in.actions';
import * as import84 from '../core/auth-token/auth-token.actions';
import * as import85 from '../core/auth-store/auth-ready.actions';
import * as import86 from '../core/profile/profile.actions';
import * as import87 from '../core/auth-token/auth-token.service';
import * as import88 from '../core/auth-http/auth-http.service';
import * as import89 from '../core/account/account.service';
import * as import90 from '../core/logger';
import * as import91 from '../core/auth-token/external-auth.service';
import * as import92 from '@ngrx/store-devtools/src/extension';
import * as import93 from '@ngrx/store-devtools/src/devtools';
import * as import94 from '@angular/router/src/router_preloader';
import * as import95 from '@angular/core/src/di/injector';
import * as import96 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import97 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import98 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import99 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import100 from './home/home.component.ngfactory';
import * as import101 from './unauthorized/unauthorized.component.ngfactory';
import * as import102 from './not-found/not-found.component.ngfactory';
import * as import103 from './app.component.ngfactory';
import * as import104 from '@angular/core/src/application_tokens';
import * as import105 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import106 from '@angular/platform-browser/src/dom/events/key_events';
import * as import107 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import108 from '@angular/core/src/zone/ng_zone';
import * as import109 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import110 from '@angular/common/src/location/platform_location';
import * as import111 from '@angular/common/src/location/location_strategy';
import * as import112 from './home/home.component';
import * as import113 from './unauthorized/unauthorized.component';
import * as import114 from './not-found/not-found.component';
import * as import115 from '@angular/router/src/url_handling_strategy';
import * as import116 from '../+admin/users/user-reducer';
import * as import117 from '../core/alert/alert.reducer';
import * as import118 from '../core/loading-bar/loading-bar.reducer';
import * as import119 from '../core/auth-store/auth.store';
import * as import120 from '@angular/router/src/router';
import * as import121 from '@angular/core/src/console';
import * as import122 from '@angular/core/src/error_handler';
import * as import123 from '@angular/core/src/i18n/tokens';
import * as import124 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import125 from '@angular/platform-browser/src/dom/animation_driver';
import * as import126 from '@angular/core/src/render/api';
import * as import127 from '@angular/core/src/security';
import * as import128 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import129 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import130 from '@angular/http/src/interfaces';
import * as import131 from '@angular/http/src/http';
import * as import132 from '@ngrx/store/src/reducer';
import * as import133 from '@ngrx/store/src/state';
import * as import134 from '@ngrx/store/src/store';
import * as import135 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import136 from '@angular/router/src/router_config_loader';
import * as import137 from '@ngrx/store-devtools/src/config';
import * as import138 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _ReactiveFormsModule_4:import6.ReactiveFormsModule;
  _HttpModule_5:import7.HttpModule;
  _MdRippleModule_6:import8.MdRippleModule;
  _MdButtonModule_7:import9.MdButtonModule;
  _MdCardModule_8:import10.MdCardModule;
  _MdCheckboxModule_9:import11.MdCheckboxModule;
  _MdLineModule_10:import12.MdLineModule;
  _MdGridListModule_11:import13.MdGridListModule;
  _FormsModule_12:import6.FormsModule;
  _MdInputModule_13:import14.MdInputModule;
  _MdListModule_14:import15.MdListModule;
  _MdProgressBarModule_15:import16.MdProgressBarModule;
  _MdProgressCircleModule_16:import17.MdProgressCircleModule;
  _MdSidenavModule_17:import18.MdSidenavModule;
  _PortalModule_18:import19.PortalModule;
  _MdTabsModule_19:import20.MdTabsModule;
  _MdToolbarModule_20:import21.MdToolbarModule;
  _RtlModule_21:import22.RtlModule;
  _A11yModule_22:import23.A11yModule;
  _MdButtonToggleModule_23:import24.MdButtonToggleModule;
  _OverlayModule_24:import25.OverlayModule;
  _MdDialogModule_25:import26.MdDialogModule;
  _MdIconModule_26:import27.MdIconModule;
  _MdMenuModule_27:import28.MdMenuModule;
  _MdRadioModule_28:import29.MdRadioModule;
  _MdSliderModule_29:import30.MdSliderModule;
  _MdSlideToggleModule_30:import31.MdSlideToggleModule;
  _MdSnackBarModule_31:import32.MdSnackBarModule;
  _MdTooltipModule_32:import33.MdTooltipModule;
  _StyleCompatibilityModule_33:import34.StyleCompatibilityModule;
  _MaterialRootModule_34:import35.MaterialRootModule;
  _MaterialModule_35:import35.MaterialModule;
  _SharedModule_36:import36.SharedModule;
  _CoreModule_37:import37.CoreModule;
  _ROUTER_FORROOT_GUARD_38:any;
  _RouterModule_39:import38.RouterModule;
  _StoreModule_40:import39.StoreModule;
  _StoreDevtoolsModule_41:import40.StoreDevtoolsModule;
  _ErrorHandler_42:any;
  _ApplicationInitStatus_43:import41.ApplicationInitStatus;
  _Testability_44:import42.Testability;
  _ApplicationRef__45:import43.ApplicationRef_;
  _ApplicationRef_46:any;
  _AppModule_47:import1.AppModule;
  __LOCALE_ID_48:any;
  __NgLocalization_49:import44.NgLocaleLocalization;
  __Compiler_50:import45.Compiler;
  __APP_ID_51:any;
  __DOCUMENT_52:any;
  __HAMMER_GESTURE_CONFIG_53:import46.MdGestureConfig;
  __EVENT_MANAGER_PLUGINS_54:any[];
  __EventManager_55:import47.EventManager;
  __DomSharedStylesHost_56:import48.DomSharedStylesHost;
  __AnimationDriver_57:any;
  __DomRootRenderer_58:import49.DomRootRenderer_;
  __RootRenderer_59:any;
  __DomSanitizer_60:import50.DomSanitizerImpl;
  __Sanitizer_61:any;
  __ViewUtils_62:import51.ViewUtils;
  __IterableDiffers_63:any;
  __KeyValueDiffers_64:any;
  __SharedStylesHost_65:any;
  __Title_66:import52.Title;
  __FormBuilder_67:import53.FormBuilder;
  __RadioControlRegistry_68:import54.RadioControlRegistry;
  __BrowserXhr_69:import55.BrowserXhr;
  __ResponseOptions_70:import56.BaseResponseOptions;
  __XSRFStrategy_71:any;
  __XHRBackend_72:import57.XHRBackend;
  __RequestOptions_73:import58.BaseRequestOptions;
  __Http_74:any;
  __MdLiveAnnouncer_75:import59.MdLiveAnnouncer;
  __InteractivityChecker_76:import60.InteractivityChecker;
  __MdUniqueSelectionDispatcher_77:import61.MdUniqueSelectionDispatcher;
  __OverlayContainer_78:import62.OverlayContainer;
  __ViewportRuler_79:import63.ViewportRuler;
  __OverlayPositionBuilder_80:import64.OverlayPositionBuilder;
  __Overlay_81:import65.Overlay;
  __MdDialog_82:import26.MdDialog;
  __MdIconRegistry_83:import66.MdIconRegistry;
  __MdSnackBar_84:import32.MdSnackBar;
  __Dispatcher_85:import67.Dispatcher;
  __REDUX_DEVTOOLS_EXTENSION_86:any;
  __Reducer_87:any;
  __State_88:any;
  __Store_89:any;
  __LoadingBarActions_90:import68.LoadingBarActions;
  __LoadingBarService_91:import69.LoadingBarService;
  __AlertActions_92:import70.AlertActions;
  __AlertService_93:import71.AlertService;
  __StorageBackend_94:import72.LocalStorageBackend;
  __Storage_95:import72.Storage;
  __ProfileService_96:import73.ProfileService;
  __UrlSerializer_97:import74.DefaultUrlSerializer;
  __RouterOutletMap_98:import75.RouterOutletMap;
  __ROUTER_CONFIGURATION_99:any;
  __LocationStrategy_100:any;
  __Location_101:import76.Location;
  __NgModuleFactoryLoader_102:import77.SystemJsNgModuleLoader;
  __ROUTES_103:any[];
  __Router_104:any;
  __AuthGuard_105:import78.AuthGuard;
  __SuperAdminAuthGuard_106:import79.SuperAdminAuthGuard;
  __AuthenticatedAuthGuard_107:import80.AuthenticatedAuthGuard;
  __HttpExceptionService_108:import81.HttpExceptionService;
  __FormValidationService_109:import82.FormValidationService;
  __LoggedInActions_110:import83.LoggedInActions;
  __AuthTokenActions_111:import84.AuthTokenActions;
  __AuthReadyActions_112:import85.AuthReadyActions;
  __ProfileActions_113:import86.ProfileActions;
  __AuthTokenService_114:import87.AuthTokenService;
  __AuthHttp_115:import88.AuthHttp;
  __AccountService_116:import89.AccountService;
  __LoggingBackend_117:import90.ConsoleLoggerBackend;
  __Logger_118:import90.Logger;
  __ExternalAuthService_119:import91.ExternalAuthService;
  __DevtoolsExtension_120:import92.DevtoolsExtension;
  __DevtoolsDispatcher_121:import93.DevtoolsDispatcher;
  ___INITIAL_STATE_122:any;
  ___INITIAL_REDUCER_123:any;
  __INITIAL_REDUCER_124:any;
  __INITIAL_STATE_125:any;
  __STORE_DEVTOOLS_CONFIG_126:any;
  __StoreDevtools_127:import93.StoreDevtools;
  __ActivatedRoute_128:any;
  _PreloadAllModules_129:import94.PreloadAllModules;
  _PreloadingStrategy_130:any;
  _RouterPreloader_131:import94.RouterPreloader;
  __NoPreloading_132:import94.NoPreloading;
  __ROUTER_INITIALIZER_133:any;
  __APP_BOOTSTRAP_LISTENER_134:any[];
  constructor(parent:import95.Injector) {
    super(parent,[
      import96.MdDialogContainerNgFactory,
      import97.MdSnackBarContainerNgFactory,
      import98.SimpleSnackBarNgFactory,
      import99.TooltipComponentNgFactory,
      import100.HomeComponentNgFactory,
      import100.HomeComponentNgFactory,
      import101.UnauthorizedComponentNgFactory,
      import102.NotFoundComponentNgFactory,
      import103.AppComponentNgFactory
    ]
    ,[import103.AppComponentNgFactory]);
  }
  get _LOCALE_ID_48():any {
    if ((this.__LOCALE_ID_48 == null)) { (this.__LOCALE_ID_48 = 'en-US'); }
    return this.__LOCALE_ID_48;
  }
  get _NgLocalization_49():import44.NgLocaleLocalization {
    if ((this.__NgLocalization_49 == null)) { (this.__NgLocalization_49 = new import44.NgLocaleLocalization(this._LOCALE_ID_48)); }
    return this.__NgLocalization_49;
  }
  get _Compiler_50():import45.Compiler {
    if ((this.__Compiler_50 == null)) { (this.__Compiler_50 = new import45.Compiler()); }
    return this.__Compiler_50;
  }
  get _APP_ID_51():any {
    if ((this.__APP_ID_51 == null)) { (this.__APP_ID_51 = import104._appIdRandomProviderFactory()); }
    return this.__APP_ID_51;
  }
  get _DOCUMENT_52():any {
    if ((this.__DOCUMENT_52 == null)) { (this.__DOCUMENT_52 = import4._document()); }
    return this.__DOCUMENT_52;
  }
  get _HAMMER_GESTURE_CONFIG_53():import46.MdGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_53 == null)) { (this.__HAMMER_GESTURE_CONFIG_53 = new import46.MdGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_53;
  }
  get _EVENT_MANAGER_PLUGINS_54():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_54 == null)) { (this.__EVENT_MANAGER_PLUGINS_54 = [
      new import105.DomEventsPlugin(),
      new import106.KeyEventsPlugin(),
      new import107.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_53)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_54;
  }
  get _EventManager_55():import47.EventManager {
    if ((this.__EventManager_55 == null)) { (this.__EventManager_55 = new import47.EventManager(this._EVENT_MANAGER_PLUGINS_54,this.parent.get(import108.NgZone))); }
    return this.__EventManager_55;
  }
  get _DomSharedStylesHost_56():import48.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_56 == null)) { (this.__DomSharedStylesHost_56 = new import48.DomSharedStylesHost(this._DOCUMENT_52)); }
    return this.__DomSharedStylesHost_56;
  }
  get _AnimationDriver_57():any {
    if ((this.__AnimationDriver_57 == null)) { (this.__AnimationDriver_57 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_57;
  }
  get _DomRootRenderer_58():import49.DomRootRenderer_ {
    if ((this.__DomRootRenderer_58 == null)) { (this.__DomRootRenderer_58 = new import49.DomRootRenderer_(this._DOCUMENT_52,this._EventManager_55,this._DomSharedStylesHost_56,this._AnimationDriver_57,this._APP_ID_51)); }
    return this.__DomRootRenderer_58;
  }
  get _RootRenderer_59():any {
    if ((this.__RootRenderer_59 == null)) { (this.__RootRenderer_59 = import109._createConditionalRootRenderer(this._DomRootRenderer_58,this.parent.get(import109.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_59;
  }
  get _DomSanitizer_60():import50.DomSanitizerImpl {
    if ((this.__DomSanitizer_60 == null)) { (this.__DomSanitizer_60 = new import50.DomSanitizerImpl()); }
    return this.__DomSanitizer_60;
  }
  get _Sanitizer_61():any {
    if ((this.__Sanitizer_61 == null)) { (this.__Sanitizer_61 = this._DomSanitizer_60); }
    return this.__Sanitizer_61;
  }
  get _ViewUtils_62():import51.ViewUtils {
    if ((this.__ViewUtils_62 == null)) { (this.__ViewUtils_62 = new import51.ViewUtils(this._RootRenderer_59,this._Sanitizer_61)); }
    return this.__ViewUtils_62;
  }
  get _IterableDiffers_63():any {
    if ((this.__IterableDiffers_63 == null)) { (this.__IterableDiffers_63 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_63;
  }
  get _KeyValueDiffers_64():any {
    if ((this.__KeyValueDiffers_64 == null)) { (this.__KeyValueDiffers_64 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_64;
  }
  get _SharedStylesHost_65():any {
    if ((this.__SharedStylesHost_65 == null)) { (this.__SharedStylesHost_65 = this._DomSharedStylesHost_56); }
    return this.__SharedStylesHost_65;
  }
  get _Title_66():import52.Title {
    if ((this.__Title_66 == null)) { (this.__Title_66 = new import52.Title()); }
    return this.__Title_66;
  }
  get _FormBuilder_67():import53.FormBuilder {
    if ((this.__FormBuilder_67 == null)) { (this.__FormBuilder_67 = new import53.FormBuilder()); }
    return this.__FormBuilder_67;
  }
  get _RadioControlRegistry_68():import54.RadioControlRegistry {
    if ((this.__RadioControlRegistry_68 == null)) { (this.__RadioControlRegistry_68 = new import54.RadioControlRegistry()); }
    return this.__RadioControlRegistry_68;
  }
  get _BrowserXhr_69():import55.BrowserXhr {
    if ((this.__BrowserXhr_69 == null)) { (this.__BrowserXhr_69 = new import55.BrowserXhr()); }
    return this.__BrowserXhr_69;
  }
  get _ResponseOptions_70():import56.BaseResponseOptions {
    if ((this.__ResponseOptions_70 == null)) { (this.__ResponseOptions_70 = new import56.BaseResponseOptions()); }
    return this.__ResponseOptions_70;
  }
  get _XSRFStrategy_71():any {
    if ((this.__XSRFStrategy_71 == null)) { (this.__XSRFStrategy_71 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_71;
  }
  get _XHRBackend_72():import57.XHRBackend {
    if ((this.__XHRBackend_72 == null)) { (this.__XHRBackend_72 = new import57.XHRBackend(this._BrowserXhr_69,this._ResponseOptions_70,this._XSRFStrategy_71)); }
    return this.__XHRBackend_72;
  }
  get _RequestOptions_73():import58.BaseRequestOptions {
    if ((this.__RequestOptions_73 == null)) { (this.__RequestOptions_73 = new import58.BaseRequestOptions()); }
    return this.__RequestOptions_73;
  }
  get _Http_74():any {
    if ((this.__Http_74 == null)) { (this.__Http_74 = import7.httpFactory(this._XHRBackend_72,this._RequestOptions_73)); }
    return this.__Http_74;
  }
  get _MdLiveAnnouncer_75():import59.MdLiveAnnouncer {
    if ((this.__MdLiveAnnouncer_75 == null)) { (this.__MdLiveAnnouncer_75 = new import59.MdLiveAnnouncer(this.parent.get(import59.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__MdLiveAnnouncer_75;
  }
  get _InteractivityChecker_76():import60.InteractivityChecker {
    if ((this.__InteractivityChecker_76 == null)) { (this.__InteractivityChecker_76 = new import60.InteractivityChecker()); }
    return this.__InteractivityChecker_76;
  }
  get _MdUniqueSelectionDispatcher_77():import61.MdUniqueSelectionDispatcher {
    if ((this.__MdUniqueSelectionDispatcher_77 == null)) { (this.__MdUniqueSelectionDispatcher_77 = new import61.MdUniqueSelectionDispatcher()); }
    return this.__MdUniqueSelectionDispatcher_77;
  }
  get _OverlayContainer_78():import62.OverlayContainer {
    if ((this.__OverlayContainer_78 == null)) { (this.__OverlayContainer_78 = new import62.OverlayContainer()); }
    return this.__OverlayContainer_78;
  }
  get _ViewportRuler_79():import63.ViewportRuler {
    if ((this.__ViewportRuler_79 == null)) { (this.__ViewportRuler_79 = new import63.ViewportRuler()); }
    return this.__ViewportRuler_79;
  }
  get _OverlayPositionBuilder_80():import64.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_80 == null)) { (this.__OverlayPositionBuilder_80 = new import64.OverlayPositionBuilder(this._ViewportRuler_79)); }
    return this.__OverlayPositionBuilder_80;
  }
  get _Overlay_81():import65.Overlay {
    if ((this.__Overlay_81 == null)) { (this.__Overlay_81 = new import65.Overlay(this._OverlayContainer_78,this,this._OverlayPositionBuilder_80,this._ApplicationRef_46,this)); }
    return this.__Overlay_81;
  }
  get _MdDialog_82():import26.MdDialog {
    if ((this.__MdDialog_82 == null)) { (this.__MdDialog_82 = new import26.MdDialog(this._Overlay_81,this)); }
    return this.__MdDialog_82;
  }
  get _MdIconRegistry_83():import66.MdIconRegistry {
    if ((this.__MdIconRegistry_83 == null)) { (this.__MdIconRegistry_83 = new import66.MdIconRegistry(this._Http_74)); }
    return this.__MdIconRegistry_83;
  }
  get _MdSnackBar_84():import32.MdSnackBar {
    if ((this.__MdSnackBar_84 == null)) { (this.__MdSnackBar_84 = new import32.MdSnackBar(this._Overlay_81,this._MdLiveAnnouncer_75)); }
    return this.__MdSnackBar_84;
  }
  get _Dispatcher_85():import67.Dispatcher {
    if ((this.__Dispatcher_85 == null)) { (this.__Dispatcher_85 = new import67.Dispatcher()); }
    return this.__Dispatcher_85;
  }
  get _REDUX_DEVTOOLS_EXTENSION_86():any {
    if ((this.__REDUX_DEVTOOLS_EXTENSION_86 == null)) { (this.__REDUX_DEVTOOLS_EXTENSION_86 = import40._createReduxDevtoolsExtension()); }
    return this.__REDUX_DEVTOOLS_EXTENSION_86;
  }
  get _Reducer_87():any {
    if ((this.__Reducer_87 == null)) { (this.__Reducer_87 = import40._createReducerIfExtension(this._REDUX_DEVTOOLS_EXTENSION_86,this)); }
    return this.__Reducer_87;
  }
  get _State_88():any {
    if ((this.__State_88 == null)) { (this.__State_88 = import40._createStateIfExtension(this._REDUX_DEVTOOLS_EXTENSION_86,this)); }
    return this.__State_88;
  }
  get _Store_89():any {
    if ((this.__Store_89 == null)) { (this.__Store_89 = import39._storeFactory(this._Dispatcher_85,this._Reducer_87,this._State_88)); }
    return this.__Store_89;
  }
  get _LoadingBarActions_90():import68.LoadingBarActions {
    if ((this.__LoadingBarActions_90 == null)) { (this.__LoadingBarActions_90 = new import68.LoadingBarActions()); }
    return this.__LoadingBarActions_90;
  }
  get _LoadingBarService_91():import69.LoadingBarService {
    if ((this.__LoadingBarService_91 == null)) { (this.__LoadingBarService_91 = new import69.LoadingBarService(this._Store_89,this._LoadingBarActions_90)); }
    return this.__LoadingBarService_91;
  }
  get _AlertActions_92():import70.AlertActions {
    if ((this.__AlertActions_92 == null)) { (this.__AlertActions_92 = new import70.AlertActions()); }
    return this.__AlertActions_92;
  }
  get _AlertService_93():import71.AlertService {
    if ((this.__AlertService_93 == null)) { (this.__AlertService_93 = new import71.AlertService(this._Store_89,this._AlertActions_92)); }
    return this.__AlertService_93;
  }
  get _StorageBackend_94():import72.LocalStorageBackend {
    if ((this.__StorageBackend_94 == null)) { (this.__StorageBackend_94 = new import72.LocalStorageBackend()); }
    return this.__StorageBackend_94;
  }
  get _Storage_95():import72.Storage {
    if ((this.__Storage_95 == null)) { (this.__Storage_95 = new import72.Storage(this._StorageBackend_94)); }
    return this.__Storage_95;
  }
  get _ProfileService_96():import73.ProfileService {
    if ((this.__ProfileService_96 == null)) { (this.__ProfileService_96 = new import73.ProfileService(this._Storage_95,this._Store_89)); }
    return this.__ProfileService_96;
  }
  get _UrlSerializer_97():import74.DefaultUrlSerializer {
    if ((this.__UrlSerializer_97 == null)) { (this.__UrlSerializer_97 = new import74.DefaultUrlSerializer()); }
    return this.__UrlSerializer_97;
  }
  get _RouterOutletMap_98():import75.RouterOutletMap {
    if ((this.__RouterOutletMap_98 == null)) { (this.__RouterOutletMap_98 = new import75.RouterOutletMap()); }
    return this.__RouterOutletMap_98;
  }
  get _ROUTER_CONFIGURATION_99():any {
    if ((this.__ROUTER_CONFIGURATION_99 == null)) { (this.__ROUTER_CONFIGURATION_99 = {preloadingStrategy: import94.PreloadAllModules}); }
    return this.__ROUTER_CONFIGURATION_99;
  }
  get _LocationStrategy_100():any {
    if ((this.__LocationStrategy_100 == null)) { (this.__LocationStrategy_100 = import38.provideLocationStrategy(this.parent.get(import110.PlatformLocation),this.parent.get(import111.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_99)); }
    return this.__LocationStrategy_100;
  }
  get _Location_101():import76.Location {
    if ((this.__Location_101 == null)) { (this.__Location_101 = new import76.Location(this._LocationStrategy_100)); }
    return this.__Location_101;
  }
  get _NgModuleFactoryLoader_102():import77.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_102 == null)) { (this.__NgModuleFactoryLoader_102 = new import77.SystemJsNgModuleLoader(this._Compiler_50,this.parent.get(import77.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_102;
  }
  get _ROUTES_103():any[] {
      if ((this.__ROUTES_103 == null)) { (this.__ROUTES_103 = [[
        {
          path: '',
          component: import112.HomeComponent
        }
        ,
        {
          path: 'home',
          component: import112.HomeComponent
        }
        ,
        {
          path: 'admin',
          loadChildren: '../+admin/admin.module#AdminModule',
          canLoad: [import79.SuperAdminAuthGuard]
        }
        ,
        {
          path: 'auth',
          loadChildren: '../+auth/auth.module#AuthModule'
        }
        ,
        {
          path: 'account',
          loadChildren: '../+account/account.module#AccountModule'
        }
        ,
        {
          path: 'unauthorized',
          component: import113.UnauthorizedComponent
        }
        ,
        {
          path: '**',
          component: import114.NotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_103;
  }
  get _Router_104():any {
    if ((this.__Router_104 == null)) { (this.__Router_104 = import38.setupRouter(this._ApplicationRef_46,this._UrlSerializer_97,this._RouterOutletMap_98,this._Location_101,this,this._NgModuleFactoryLoader_102,this._Compiler_50,this._ROUTES_103,this._ROUTER_CONFIGURATION_99,this.parent.get(import115.UrlHandlingStrategy,(null as any)))); }
    return this.__Router_104;
  }
  get _AuthGuard_105():import78.AuthGuard {
    if ((this.__AuthGuard_105 == null)) { (this.__AuthGuard_105 = new import78.AuthGuard(this._Router_104,this._AlertService_93,this._ProfileService_96,this._Store_89)); }
    return this.__AuthGuard_105;
  }
  get _SuperAdminAuthGuard_106():import79.SuperAdminAuthGuard {
    if ((this.__SuperAdminAuthGuard_106 == null)) { (this.__SuperAdminAuthGuard_106 = new import79.SuperAdminAuthGuard(this._AuthGuard_105)); }
    return this.__SuperAdminAuthGuard_106;
  }
  get _AuthenticatedAuthGuard_107():import80.AuthenticatedAuthGuard {
    if ((this.__AuthenticatedAuthGuard_107 == null)) { (this.__AuthenticatedAuthGuard_107 = new import80.AuthenticatedAuthGuard(this._AuthGuard_105)); }
    return this.__AuthenticatedAuthGuard_107;
  }
  get _HttpExceptionService_108():import81.HttpExceptionService {
    if ((this.__HttpExceptionService_108 == null)) { (this.__HttpExceptionService_108 = new import81.HttpExceptionService()); }
    return this.__HttpExceptionService_108;
  }
  get _FormValidationService_109():import82.FormValidationService {
    if ((this.__FormValidationService_109 == null)) { (this.__FormValidationService_109 = new import82.FormValidationService()); }
    return this.__FormValidationService_109;
  }
  get _LoggedInActions_110():import83.LoggedInActions {
    if ((this.__LoggedInActions_110 == null)) { (this.__LoggedInActions_110 = new import83.LoggedInActions()); }
    return this.__LoggedInActions_110;
  }
  get _AuthTokenActions_111():import84.AuthTokenActions {
    if ((this.__AuthTokenActions_111 == null)) { (this.__AuthTokenActions_111 = new import84.AuthTokenActions()); }
    return this.__AuthTokenActions_111;
  }
  get _AuthReadyActions_112():import85.AuthReadyActions {
    if ((this.__AuthReadyActions_112 == null)) { (this.__AuthReadyActions_112 = new import85.AuthReadyActions()); }
    return this.__AuthReadyActions_112;
  }
  get _ProfileActions_113():import86.ProfileActions {
    if ((this.__ProfileActions_113 == null)) { (this.__ProfileActions_113 = new import86.ProfileActions()); }
    return this.__ProfileActions_113;
  }
  get _AuthTokenService_114():import87.AuthTokenService {
    if ((this.__AuthTokenService_114 == null)) { (this.__AuthTokenService_114 = new import87.AuthTokenService(this._Storage_95,this._LoadingBarService_91,this._Http_74,this._HttpExceptionService_108,this._Store_89,this._AlertService_93,this._LoggedInActions_110,this._AuthTokenActions_111,this._AuthReadyActions_112,this._ProfileActions_113)); }
    return this.__AuthTokenService_114;
  }
  get _AuthHttp_115():import88.AuthHttp {
    if ((this.__AuthHttp_115 == null)) { (this.__AuthHttp_115 = new import88.AuthHttp(this._Http_74,this._Store_89,this._HttpExceptionService_108,this._LoadingBarService_91)); }
    return this.__AuthHttp_115;
  }
  get _AccountService_116():import89.AccountService {
    if ((this.__AccountService_116 == null)) { (this.__AccountService_116 = new import89.AccountService(this._LoadingBarService_91,this._Http_74,this._HttpExceptionService_108,this._AuthHttp_115,this._AuthTokenService_114,this._Store_89,this._LoggedInActions_110,this._AuthTokenActions_111,this._ProfileActions_113)); }
    return this.__AccountService_116;
  }
  get _LoggingBackend_117():import90.ConsoleLoggerBackend {
    if ((this.__LoggingBackend_117 == null)) { (this.__LoggingBackend_117 = new import90.ConsoleLoggerBackend(this._Store_89)); }
    return this.__LoggingBackend_117;
  }
  get _Logger_118():import90.Logger {
    if ((this.__Logger_118 == null)) { (this.__Logger_118 = new import90.Logger(this._LoggingBackend_117)); }
    return this.__Logger_118;
  }
  get _ExternalAuthService_119():import91.ExternalAuthService {
    if ((this.__ExternalAuthService_119 == null)) { (this.__ExternalAuthService_119 = new import91.ExternalAuthService(this._Http_74,this._Logger_118,this._AccountService_116)); }
    return this.__ExternalAuthService_119;
  }
  get _DevtoolsExtension_120():import92.DevtoolsExtension {
    if ((this.__DevtoolsExtension_120 == null)) { (this.__DevtoolsExtension_120 = new import92.DevtoolsExtension(this._REDUX_DEVTOOLS_EXTENSION_86)); }
    return this.__DevtoolsExtension_120;
  }
  get _DevtoolsDispatcher_121():import93.DevtoolsDispatcher {
    if ((this.__DevtoolsDispatcher_121 == null)) { (this.__DevtoolsDispatcher_121 = new import93.DevtoolsDispatcher()); }
    return this.__DevtoolsDispatcher_121;
  }
  get __INITIAL_STATE_122():any {
    if ((this.___INITIAL_STATE_122 == null)) { (this.___INITIAL_STATE_122 = (undefined as any)); }
    return this.___INITIAL_STATE_122;
  }
  get __INITIAL_REDUCER_123():any {
    if ((this.___INITIAL_REDUCER_123 == null)) { (this.___INITIAL_REDUCER_123 = {
      users: import116.usersReducer,
      alerts: import117.alertReducer,
      loading: import118.loadingBarReducer,
      auth: import119.authReducer
    }
    ); }
    return this.___INITIAL_REDUCER_123;
  }
  get _INITIAL_REDUCER_124():any {
    if ((this.__INITIAL_REDUCER_124 == null)) { (this.__INITIAL_REDUCER_124 = import39._initialReducerFactory(this.__INITIAL_REDUCER_123)); }
    return this.__INITIAL_REDUCER_124;
  }
  get _INITIAL_STATE_125():any {
    if ((this.__INITIAL_STATE_125 == null)) { (this.__INITIAL_STATE_125 = import39._initialStateFactory(this.__INITIAL_STATE_122,this._INITIAL_REDUCER_124)); }
    return this.__INITIAL_STATE_125;
  }
  get _STORE_DEVTOOLS_CONFIG_126():any {
    if ((this.__STORE_DEVTOOLS_CONFIG_126 == null)) { (this.__STORE_DEVTOOLS_CONFIG_126 = import40._createExtensionOptions()); }
    return this.__STORE_DEVTOOLS_CONFIG_126;
  }
  get _StoreDevtools_127():import93.StoreDevtools {
    if ((this.__StoreDevtools_127 == null)) { (this.__StoreDevtools_127 = new import93.StoreDevtools(this._DevtoolsDispatcher_121,this._Dispatcher_85,this._Reducer_87,this._DevtoolsExtension_120,this._INITIAL_STATE_125,this._STORE_DEVTOOLS_CONFIG_126)); }
    return this.__StoreDevtools_127;
  }
  get _ActivatedRoute_128():any {
    if ((this.__ActivatedRoute_128 == null)) { (this.__ActivatedRoute_128 = import38.rootRoute(this._Router_104)); }
    return this.__ActivatedRoute_128;
  }
  get _NoPreloading_132():import94.NoPreloading {
    if ((this.__NoPreloading_132 == null)) { (this.__NoPreloading_132 = new import94.NoPreloading()); }
    return this.__NoPreloading_132;
  }
  get _ROUTER_INITIALIZER_133():any {
    if ((this.__ROUTER_INITIALIZER_133 == null)) { (this.__ROUTER_INITIALIZER_133 = import38.initialRouterNavigation(this._Router_104,this._ApplicationRef_46,this._RouterPreloader_131,this._ROUTER_CONFIGURATION_99)); }
    return this.__ROUTER_INITIALIZER_133;
  }
  get _APP_BOOTSTRAP_LISTENER_134():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_134 == null)) { (this.__APP_BOOTSTRAP_LISTENER_134 = [this._ROUTER_INITIALIZER_133]); }
    return this.__APP_BOOTSTRAP_LISTENER_134;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._ReactiveFormsModule_4 = new import6.ReactiveFormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._MdRippleModule_6 = new import8.MdRippleModule();
    this._MdButtonModule_7 = new import9.MdButtonModule();
    this._MdCardModule_8 = new import10.MdCardModule();
    this._MdCheckboxModule_9 = new import11.MdCheckboxModule();
    this._MdLineModule_10 = new import12.MdLineModule();
    this._MdGridListModule_11 = new import13.MdGridListModule();
    this._FormsModule_12 = new import6.FormsModule();
    this._MdInputModule_13 = new import14.MdInputModule();
    this._MdListModule_14 = new import15.MdListModule();
    this._MdProgressBarModule_15 = new import16.MdProgressBarModule();
    this._MdProgressCircleModule_16 = new import17.MdProgressCircleModule();
    this._MdSidenavModule_17 = new import18.MdSidenavModule();
    this._PortalModule_18 = new import19.PortalModule();
    this._MdTabsModule_19 = new import20.MdTabsModule();
    this._MdToolbarModule_20 = new import21.MdToolbarModule();
    this._RtlModule_21 = new import22.RtlModule();
    this._A11yModule_22 = new import23.A11yModule();
    this._MdButtonToggleModule_23 = new import24.MdButtonToggleModule();
    this._OverlayModule_24 = new import25.OverlayModule();
    this._MdDialogModule_25 = new import26.MdDialogModule();
    this._MdIconModule_26 = new import27.MdIconModule();
    this._MdMenuModule_27 = new import28.MdMenuModule();
    this._MdRadioModule_28 = new import29.MdRadioModule();
    this._MdSliderModule_29 = new import30.MdSliderModule();
    this._MdSlideToggleModule_30 = new import31.MdSlideToggleModule();
    this._MdSnackBarModule_31 = new import32.MdSnackBarModule();
    this._MdTooltipModule_32 = new import33.MdTooltipModule();
    this._StyleCompatibilityModule_33 = new import34.StyleCompatibilityModule();
    this._MaterialRootModule_34 = new import35.MaterialRootModule();
    this._MaterialModule_35 = new import35.MaterialModule();
    this._SharedModule_36 = new import36.SharedModule();
    this._CoreModule_37 = new import37.CoreModule(this.parent.get(import37.CoreModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_38 = import38.provideForRootGuard(this.parent.get(import120.Router,(null as any)));
    this._RouterModule_39 = new import38.RouterModule(this._ROUTER_FORROOT_GUARD_38);
    this._StoreModule_40 = new import39.StoreModule();
    this._StoreDevtoolsModule_41 = new import40.StoreDevtoolsModule();
    this._ErrorHandler_42 = import4.errorHandler();
    this._ApplicationInitStatus_43 = new import41.ApplicationInitStatus(this.parent.get(import41.APP_INITIALIZER,(null as any)));
    this._Testability_44 = new import42.Testability(this.parent.get(import108.NgZone));
    this._ApplicationRef__45 = new import43.ApplicationRef_(this.parent.get(import108.NgZone),this.parent.get(import121.Console),this,this._ErrorHandler_42,this,this._ApplicationInitStatus_43,this.parent.get(import42.TestabilityRegistry,(null as any)),this._Testability_44);
    this._ApplicationRef_46 = this._ApplicationRef__45;
    this._AppModule_47 = new import1.AppModule(this._ApplicationRef_46);
    this._PreloadAllModules_129 = new import94.PreloadAllModules();
    this._PreloadingStrategy_130 = this._PreloadAllModules_129;
    this._RouterPreloader_131 = new import94.RouterPreloader(this._Router_104,this._NgModuleFactoryLoader_102,this._Compiler_50,this,this._PreloadingStrategy_130);
    return this._AppModule_47;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.MdRippleModule)) { return this._MdRippleModule_6; }
    if ((token === import9.MdButtonModule)) { return this._MdButtonModule_7; }
    if ((token === import10.MdCardModule)) { return this._MdCardModule_8; }
    if ((token === import11.MdCheckboxModule)) { return this._MdCheckboxModule_9; }
    if ((token === import12.MdLineModule)) { return this._MdLineModule_10; }
    if ((token === import13.MdGridListModule)) { return this._MdGridListModule_11; }
    if ((token === import6.FormsModule)) { return this._FormsModule_12; }
    if ((token === import14.MdInputModule)) { return this._MdInputModule_13; }
    if ((token === import15.MdListModule)) { return this._MdListModule_14; }
    if ((token === import16.MdProgressBarModule)) { return this._MdProgressBarModule_15; }
    if ((token === import17.MdProgressCircleModule)) { return this._MdProgressCircleModule_16; }
    if ((token === import18.MdSidenavModule)) { return this._MdSidenavModule_17; }
    if ((token === import19.PortalModule)) { return this._PortalModule_18; }
    if ((token === import20.MdTabsModule)) { return this._MdTabsModule_19; }
    if ((token === import21.MdToolbarModule)) { return this._MdToolbarModule_20; }
    if ((token === import22.RtlModule)) { return this._RtlModule_21; }
    if ((token === import23.A11yModule)) { return this._A11yModule_22; }
    if ((token === import24.MdButtonToggleModule)) { return this._MdButtonToggleModule_23; }
    if ((token === import25.OverlayModule)) { return this._OverlayModule_24; }
    if ((token === import26.MdDialogModule)) { return this._MdDialogModule_25; }
    if ((token === import27.MdIconModule)) { return this._MdIconModule_26; }
    if ((token === import28.MdMenuModule)) { return this._MdMenuModule_27; }
    if ((token === import29.MdRadioModule)) { return this._MdRadioModule_28; }
    if ((token === import30.MdSliderModule)) { return this._MdSliderModule_29; }
    if ((token === import31.MdSlideToggleModule)) { return this._MdSlideToggleModule_30; }
    if ((token === import32.MdSnackBarModule)) { return this._MdSnackBarModule_31; }
    if ((token === import33.MdTooltipModule)) { return this._MdTooltipModule_32; }
    if ((token === import34.StyleCompatibilityModule)) { return this._StyleCompatibilityModule_33; }
    if ((token === import35.MaterialRootModule)) { return this._MaterialRootModule_34; }
    if ((token === import35.MaterialModule)) { return this._MaterialModule_35; }
    if ((token === import36.SharedModule)) { return this._SharedModule_36; }
    if ((token === import37.CoreModule)) { return this._CoreModule_37; }
    if ((token === import38.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_38; }
    if ((token === import38.RouterModule)) { return this._RouterModule_39; }
    if ((token === import39.StoreModule)) { return this._StoreModule_40; }
    if ((token === import40.StoreDevtoolsModule)) { return this._StoreDevtoolsModule_41; }
    if ((token === import122.ErrorHandler)) { return this._ErrorHandler_42; }
    if ((token === import41.ApplicationInitStatus)) { return this._ApplicationInitStatus_43; }
    if ((token === import42.Testability)) { return this._Testability_44; }
    if ((token === import43.ApplicationRef_)) { return this._ApplicationRef__45; }
    if ((token === import43.ApplicationRef)) { return this._ApplicationRef_46; }
    if ((token === import1.AppModule)) { return this._AppModule_47; }
    if ((token === import123.LOCALE_ID)) { return this._LOCALE_ID_48; }
    if ((token === import44.NgLocalization)) { return this._NgLocalization_49; }
    if ((token === import45.Compiler)) { return this._Compiler_50; }
    if ((token === import104.APP_ID)) { return this._APP_ID_51; }
    if ((token === import124.DOCUMENT)) { return this._DOCUMENT_52; }
    if ((token === import107.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_53; }
    if ((token === import47.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_54; }
    if ((token === import47.EventManager)) { return this._EventManager_55; }
    if ((token === import48.DomSharedStylesHost)) { return this._DomSharedStylesHost_56; }
    if ((token === import125.AnimationDriver)) { return this._AnimationDriver_57; }
    if ((token === import49.DomRootRenderer)) { return this._DomRootRenderer_58; }
    if ((token === import126.RootRenderer)) { return this._RootRenderer_59; }
    if ((token === import50.DomSanitizer)) { return this._DomSanitizer_60; }
    if ((token === import127.Sanitizer)) { return this._Sanitizer_61; }
    if ((token === import51.ViewUtils)) { return this._ViewUtils_62; }
    if ((token === import128.IterableDiffers)) { return this._IterableDiffers_63; }
    if ((token === import129.KeyValueDiffers)) { return this._KeyValueDiffers_64; }
    if ((token === import48.SharedStylesHost)) { return this._SharedStylesHost_65; }
    if ((token === import52.Title)) { return this._Title_66; }
    if ((token === import53.FormBuilder)) { return this._FormBuilder_67; }
    if ((token === import54.RadioControlRegistry)) { return this._RadioControlRegistry_68; }
    if ((token === import55.BrowserXhr)) { return this._BrowserXhr_69; }
    if ((token === import56.ResponseOptions)) { return this._ResponseOptions_70; }
    if ((token === import130.XSRFStrategy)) { return this._XSRFStrategy_71; }
    if ((token === import57.XHRBackend)) { return this._XHRBackend_72; }
    if ((token === import58.RequestOptions)) { return this._RequestOptions_73; }
    if ((token === import131.Http)) { return this._Http_74; }
    if ((token === import59.MdLiveAnnouncer)) { return this._MdLiveAnnouncer_75; }
    if ((token === import60.InteractivityChecker)) { return this._InteractivityChecker_76; }
    if ((token === import61.MdUniqueSelectionDispatcher)) { return this._MdUniqueSelectionDispatcher_77; }
    if ((token === import62.OverlayContainer)) { return this._OverlayContainer_78; }
    if ((token === import63.ViewportRuler)) { return this._ViewportRuler_79; }
    if ((token === import64.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_80; }
    if ((token === import65.Overlay)) { return this._Overlay_81; }
    if ((token === import26.MdDialog)) { return this._MdDialog_82; }
    if ((token === import66.MdIconRegistry)) { return this._MdIconRegistry_83; }
    if ((token === import32.MdSnackBar)) { return this._MdSnackBar_84; }
    if ((token === import67.Dispatcher)) { return this._Dispatcher_85; }
    if ((token === import92.REDUX_DEVTOOLS_EXTENSION)) { return this._REDUX_DEVTOOLS_EXTENSION_86; }
    if ((token === import132.Reducer)) { return this._Reducer_87; }
    if ((token === import133.State)) { return this._State_88; }
    if ((token === import134.Store)) { return this._Store_89; }
    if ((token === import68.LoadingBarActions)) { return this._LoadingBarActions_90; }
    if ((token === import69.LoadingBarService)) { return this._LoadingBarService_91; }
    if ((token === import70.AlertActions)) { return this._AlertActions_92; }
    if ((token === import71.AlertService)) { return this._AlertService_93; }
    if ((token === import72.StorageBackend)) { return this._StorageBackend_94; }
    if ((token === import72.Storage)) { return this._Storage_95; }
    if ((token === import73.ProfileService)) { return this._ProfileService_96; }
    if ((token === import74.UrlSerializer)) { return this._UrlSerializer_97; }
    if ((token === import75.RouterOutletMap)) { return this._RouterOutletMap_98; }
    if ((token === import38.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_99; }
    if ((token === import111.LocationStrategy)) { return this._LocationStrategy_100; }
    if ((token === import76.Location)) { return this._Location_101; }
    if ((token === import135.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_102; }
    if ((token === import136.ROUTES)) { return this._ROUTES_103; }
    if ((token === import120.Router)) { return this._Router_104; }
    if ((token === import78.AuthGuard)) { return this._AuthGuard_105; }
    if ((token === import79.SuperAdminAuthGuard)) { return this._SuperAdminAuthGuard_106; }
    if ((token === import80.AuthenticatedAuthGuard)) { return this._AuthenticatedAuthGuard_107; }
    if ((token === import81.HttpExceptionService)) { return this._HttpExceptionService_108; }
    if ((token === import82.FormValidationService)) { return this._FormValidationService_109; }
    if ((token === import83.LoggedInActions)) { return this._LoggedInActions_110; }
    if ((token === import84.AuthTokenActions)) { return this._AuthTokenActions_111; }
    if ((token === import85.AuthReadyActions)) { return this._AuthReadyActions_112; }
    if ((token === import86.ProfileActions)) { return this._ProfileActions_113; }
    if ((token === import87.AuthTokenService)) { return this._AuthTokenService_114; }
    if ((token === import88.AuthHttp)) { return this._AuthHttp_115; }
    if ((token === import89.AccountService)) { return this._AccountService_116; }
    if ((token === import90.LoggingBackend)) { return this._LoggingBackend_117; }
    if ((token === import90.Logger)) { return this._Logger_118; }
    if ((token === import91.ExternalAuthService)) { return this._ExternalAuthService_119; }
    if ((token === import92.DevtoolsExtension)) { return this._DevtoolsExtension_120; }
    if ((token === import93.DevtoolsDispatcher)) { return this._DevtoolsDispatcher_121; }
    if ((token === import39._INITIAL_STATE)) { return this.__INITIAL_STATE_122; }
    if ((token === import39._INITIAL_REDUCER)) { return this.__INITIAL_REDUCER_123; }
    if ((token === import39.INITIAL_REDUCER)) { return this._INITIAL_REDUCER_124; }
    if ((token === import39.INITIAL_STATE)) { return this._INITIAL_STATE_125; }
    if ((token === import137.STORE_DEVTOOLS_CONFIG)) { return this._STORE_DEVTOOLS_CONFIG_126; }
    if ((token === import93.StoreDevtools)) { return this._StoreDevtools_127; }
    if ((token === import138.ActivatedRoute)) { return this._ActivatedRoute_128; }
    if ((token === import94.PreloadAllModules)) { return this._PreloadAllModules_129; }
    if ((token === import94.PreloadingStrategy)) { return this._PreloadingStrategy_130; }
    if ((token === import94.RouterPreloader)) { return this._RouterPreloader_131; }
    if ((token === import94.NoPreloading)) { return this._NoPreloading_132; }
    if ((token === import38.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_133; }
    if ((token === import104.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_134; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__45.ngOnDestroy();
    this._RouterPreloader_131.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);