/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['$primary-color : rgb(124, 77, 255);\r\n\r\nbody{\r\n  font-family: Arial, serif;\r\n}\r\n\r\n.flex-grid {\r\n  display: flex;\r\n}\r\n.col {\r\n  flex: 1;\r\n}\r\n'];